import NavBarComponent from "../Components/NavBarComponent"
import "./global.css";

export const metadata = {
  title: 'NotesApp',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav className="navbar">
          <h1 className="title">NotesApp</h1>
          <div className="nav-components">
            <NavBarComponent title="Home" link="/" />
            <NavBarComponent title="Notes" link="/notes" />
            <NavBarComponent title="Random" link="/random" />
          </div>
        </nav>
        <div className="main">
          <div className="page">
            {children}
          </div>
        </div>
        <footer className="footer">
          <h3>Made with caffeine and questionable coding practices</h3>
        </footer>
      </body>
    </html>
  )
}
