import NavBarComponent from "./NavBarComponent"
import "./global.css";

export const metadata = {
  title: 'NotesApp',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav className="">
          <h1 className="nav-component">NotesApp</h1>
          <div className="nav-links">
            <NavBarComponent title="Home" link="/" />
            <NavBarComponent title="Notes" link="/notes" />
            <NavBarComponent title="Random" link="/random" />
          </div>
        </nav>
        <div id="page-container">
          <div id="content-wrap">
            {children}
          </div>
            <footer id='footer'>
              <h3>Made with caffeine and questionable coding practices</h3>
            </footer>
        </div>
      </body>
    </html>
  )
}
